version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: FileStorage
    ports:
      - "9090:9090"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    container_name: Mongo
    image: mongo:latest
    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: